image: node:12

cache:
  paths:
    - node_modules/

before_script:
  - yarn

pages:
  stage: deploy
  script:
    - PUBLIC_URL=$CI_PAGES_URL yarn build
    - cp -a build/. public
  artifacts:
    paths:
      - public
  only:
    - master
