image: node:12

cache:
  paths:
    - node_modules/

before_script:
  - yarn

pages:
  script:
    - yarn build
    - cp -r build/*.* public
  artifacts:
    paths:
      - public
  only:
    - master
